config/routes.rb
Rails.application.routes.draw do
  resources :markets do
    member do
      post :update_buy
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/market.rb
class Market < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  def index
    @markets = Market.all
  end

  def update_buy
    market = Market.find(params[:id])

    response = RestClient.get "https://bb.otcbtc.com/api/v2/tickers"
    data = JSON.parse(response.body)
    market.update(:current_buy => data['eos_cny']['ticker']['buy'])

    redirect_to markets_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiOtcbtcMarkets</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/markets/index.html.erb
<table class="table">
  <tr>
    <th>OTCBTC ID</th>
    <th>Ticker ID</th>
    <th>Name</th>
    <th>Buy</th>
  </tr>
  <% @markets.each do |market| %>
    <tr>
      <td><%= market.otcbtc_id %></td>
      <td><%= market.ticker_id %></td>
      <td><%= market.name %></td>
      <td>
        <%= market.current_buy %>
        <%= link_to "更新现价", update_buy_market_path(market), :method => :post %>
      </td>
    </tr>
  <% end %>
</table>